# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ["16"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Cache deps
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ matrix.node_version }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: install ng cli
        run: npm install -g @angular/cli

      - name: install Dependencies
        run: npm install

      - name: lint
        run: ng lint

      - name: test
        run: ng test --watch=false --browsers=ChromeHeadless

      - name: build
        run: ng build --prod --base-href=/NgDemo/

      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: yexiaorain@gmail.com
          build_dir: dist/ng-demo/
